My Project: swSeismo Namespace Reference
swSeismo Namespace Reference
Classes
class Oat
Functions
def swVersion
def swCSS3Temp (sta, iphase, time, deltim, evInfo, fp)
def swBasename (file)
def swCleanupLoc ()
def swGetSacOriginTime (kzdate, kztime, o)
def swGetSacReferTime (kzdate, kztime)
def swAicClean ()
def swSacHeader2miniArrival
def datetimefmt (origin)
format the time, e.g., 1999-01-31, 00:12:24.123
def evtoat (oatfile, evtfile)
extract event information from a oatfile
def staoat (oatfile, stafile)
extract station information from a oatfile
def ga2oat (arrfile, oatfile, stafile)
convert arrival from Geoscience Australia to oat
def oat2kml (oatfile, kmlfile)
convert oat to KML, this function depends on the package simplekml please see https://pypi.python.org/pypi/simplekml/1.2.8
Function Documentation
def swSeismo.datetimefmt (origin)
format the time, e.g., 1999-01-31, 00:12:24.123
Parameters
origin a string e.g., "1999-01-31T00:12:24.123456Z" return [date, time]
Referenced by naloc3d.naloc3().
def swSeismo.evtoat (oatfile, evtfile)
extract event information from a oatfile
Parameters
oatfile oatfile name
evtfile evtfile name
def swSeismo.ga2oat (arrfile, oatfile, stafile)
convert arrival from Geoscience Australia to oat
Parameters
arrfile arrival filename of GA
oatfile output oat filename
stafile input filename containing all station name and its lat, lon, ele, format is knetwk kstnm stla stlo stel
def swSeismo.oat2kml (oatfile, kmlfile)
convert oat to KML, this function depends on the package simplekml please see https://pypi.python.org/pypi/simplekml/1.2.8
Parameters
oatfile oat filename
kmlfile kml filename
def swSeismo.staoat (oatfile, stafile)
extract station information from a oatfile
Parameters
oatfile oatfile name
stafile evtfile name
def swSeismo.swAicClean ()
def swSeismo.swBasename (file)
file = /usr/local/test.txt
returns /usr/local, test, .txt
def swSeismo.swCleanupLoc ()
Referenced by naloc3d.naloc3().
def swSeismo.swCSS3Temp (sta, iphase, time, deltim, evInfo, fp)
Generate a peseudo CSS3.0 arrival file to fool comptuter
This is for relocation program by Dr de Kool.
Referenced by naloc3d.oat2css().
def swSeismo.swGetSacOriginTime (kzdate, kztime, o)
Referenced by swSacHeader2miniArrival().
def swSeismo.swGetSacReferTime (kzdate, kztime)
Referenced by swSacHeader2miniArrival().
def swSeismo.swSacHeader2miniArrival (sacfile, fp, mode = 'P')
get event header and station header, pick, from sac fiel
def swSeismo.swVersion (val = 1)